# Generated by Django 5.1.5 on 2025-01-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='Profile_Image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
