# Generated by Django 5.1.5 on 2025-01-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_ID', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Company', models.CharField(blank=True, max_length=150, null=True)),
                ('Salary', models.IntegerField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
